---
title: "Easy Examples Exploring Bayesian Methods"
author: "Nathan (Nat) Goodman"
date: "September 27, 2019"
output:
  html_document:
    css: css/html_document.css
    highlight: kate
  github_document:
    html_preview: no
  pdf_document: default
linkcolor: cyan
citecolor: green
urlcolor: blue
---
<!-- README.md is generated from README.Rmd. Please edit that file -->

A collection of R scripts and documents exploring Bayesian methods through easy examples. The content at present is a blog post in progress that uses Bayesian methods to estimate true effect size.  More TBD.

- blog post [What's the Effect Size? It Depends What You Think](https://natgoodman.github.io/bayez/effit.stable.html) using Bayesian methods to estimate true effect size in two group difference-of-mean studies

- working paper [Bayesian Basics](https://natgoodman.github.io/bayez/baysx.stable.html) with a simple R implementation of Bayes's formula

**THE SOFTWARE IS A WORK IN PROGRESS. THE CODE IS ROUGH and SOFTWARE DOCUMENTATION NONEXISTENT. MUCH OF THE CODE DOESN'T WORK!! PLEASE GET IN TOUCH IF YOU NEED HELP**

## Installation and Usage

The software is **not a package** and cannot be installed by `devtools::install_github` or related. Sorry. The simplest way to get the software is to download or clone the entire repo.

More TBD.

## Comments Please!

Please post comments on [Twitter](https://twitter.com/gnatgoodman) or [Facebook](https://www.facebook.com/nathan.goodman.3367), or contact me by email [natg@shore.net](mailto:natg@shore.net). 

Please report bugs, other software problems, and feature requests using the [GitHub Issue Tracker](https://github.com/natgoodman/bayez/issues). I will be notified, and you'll be apprised of progress. As already noted, the software is still rough and software documentation nonexistent.

## Copyright & License

Copyright (c) 2019 Nathan Goodman

The software is **open source and free**, released under the [MIT License](https://opensource.org/licenses/MIT). The documentation is **open access**, released under the [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0).
